name: atn_net_enc

debug:
  cb_n_batches: 50
  stop_at: null
  save_img: false

data:
  grid_dim: 16
  grid_step: 0.5
  max_atoms: 38
  max_valence: 6

model:
  name: vae
  optimizer: adam
  learn_rate: 1e-4
  latent_size: 512
  hidden_size: 512
  net:
    name: atn_net
    atom_embed_size: 32
    atom_enc_size: 32
    kp_filter_list:
      - 2
      - 4
      - 8
      - 16
      - 32
    kp_enc_size: 128
    final_enc_size: 128
    init_filters: 2
    num_gru_layers: 1
    gru_hidden_size: 512
    gru_embed_size: 64
  loss:
    kl_lambda: 0.0
    l2_lambda: 1.0
    kp_ce_lambda: 1.0
    atom_ce_lambda: 1.0

dataset: zinc
batch_size: 8
grad_clip: 0

defaults:
  - platform: local
