name: test

hydra:
  run:
    dir: ./

debug:
  cb_n_batches: 32
  checkpoint_n_batches: 128
  stop_at: null
  save_img: false
  mol_cb_enable: true

# data:
#   grid_dim: 16
#   grid_step: 0.5
#   max_atoms: 38
#   max_valence: 6

data:
  grid_dim: 8
  grid_step: 0.5
  max_atoms: 16
  max_valence: 6

model:
  name: vae
  optimizer: adamw
  learn_rate: 1e-3
  latent_size: 512
  hidden_size: 512
  net:
    name: ar_net
    atom_embed_size: 32
    atom_enc_size: 32
    valence_embed_size: 32
    valence_enc_size: 32
    kp_filter_list:
      - 2
      - 4
      - 8
    kp_enc_size: 128
    final_enc_size: 128
    num_gru_layers: 1
    num_gru_directions: 1
    enc_rnn_size: 128

    dec_lat_fc_size: 128
    dec_rnn_size: 128
    initial_dec_size: 128
    bond_pred_filters: 8
    bond_pred_heads: 16

  scheduler:
    type: null
    min_lr: 1e-6
    max_lr: 0.2
    step_size: 2000
    
  loss:
    kl_lambda: 0.1
    l2_lambda: 1.0
    kp_ce_lambda: 1.0
    atom_ce_lambda: 1.0
    bv_ce_lambda: 2.0
    bond_ce_lambda: 0.0
    bond_focal_lambda: 0.0
    valence_ce_lambda: 1.0

dataset: zinc
batch_size: 64
grad_clip: 0

test:
  run_id: MOL-148
  use_cache: false

defaults:
  - platform: local
