name: kp2mg_atypes

debug:
  cb_n_batches: 50
  stop_at: null
  save_img: false

data:
  grid_dim: 16
  grid_step: 0.5
  max_atoms: 38
  max_valence: 6

model:
  name: vae
  optimizer: adam
  learn_rate: 1e-4
  latent_size: 512
  hidden_size: 512
  net:
    name: kp_rnn
    init_filters: 2
  loss:
    kl_lambda: 1.0
    l2_lambda: 1.0

dataset: zinc
batch_size: 16
grad_clip: 0.01

defaults:
  - platform: local
