name: molgrid_test

data:
  grid_dim: 16
  grid_step: 0.5
  max_atoms: 38
  max_valence: 6

model:
  name: vae
  optimizer: adam
  learn_rate: 1e-4
  latent_size: 1024
  hidden_size: 2048
  net:
    name: basic
    init_filters: 32
  loss:
    kl_lambda: 0.0
    l2_lambda: 1.0

dataset: zinc
batch_size: 16

defaults:
  - platform: local
