grid_dim: 16
grid_step: 0.5
max_atoms: 38
max_valence: 6

# cfg:
#   num_workers: 8
#   stop_at: null

#   zinc_dir: "/home/boris/Data/Zinc/"
#   zinc_filtered_list: "/home/boris/Data/Zinc/files_filtered_both.txt"

defaults:
  - platform: standard
