name: rot_zinc8

debug:
  cb_n_batches: 4
  stop_at: null
  save_img: false

# data:
#   grid_dim: 16
#   grid_step: 0.5
#   max_atoms: 38
#   max_valence: 6

data:
  grid_dim: 8
  grid_step: 0.5
  max_atoms: 8
  max_valence: 6

model:
  name: vae
  optimizer: adam
  learn_rate: 1e-3
  latent_size: 1024
  hidden_size: 1024
  net:
    name: atn_net
    atom_embed_size: 32
    atom_enc_size: 32
    kp_filter_list:
      - 2
      - 4
      - 8
    kp_enc_size: 128
    final_enc_size: 128
    num_gru_layers: 1

    dec_lat_fc_size: 128
    dec_rnn_size: 128
    initial_dec_size: 128
    bond_pred_filters: 16
    
  loss:
    kl_lambda: 0.0
    l2_lambda: 1.0
    kp_ce_lambda: 1.0
    atom_ce_lambda: 1.0

dataset: zinc
batch_size: 32
grad_clip: 0

defaults:
  - platform: local
